name: coofisam360

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: coofisam_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Alejito10.
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
    networks: [coofinet]

  backend:
    build:
      context: ../coofisam360/backend
      dockerfile: Dockerfile
    environment:
      DJANGO_DEBUG: "False"
      DJANGO_ALLOWED_HOSTS: backend,localhost,127.0.0.1
      DB_NAME: coofisam_db
      DB_USER: postgres
      DB_PASSWORD: Alejito10.
      DB_HOST: host.docker.internal
      DB_PORT: "5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on: []
    ports:
      - "8060:8060"
    volumes:
      - lbalance:/home/desarrollo/Coofisam/data/Libro_de_Balance_x_Aanoo
    restart: unless-stopped
    networks: [coofinet]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE: https://coofisam360.ngrok.io
    environment:
      NEXT_PUBLIC_API_BASE: https://coofisam360.ngrok.io
    ports:
      - "8061:8061"
    restart: unless-stopped
    networks: [coofinet]

volumes:
  pgdata:
  lbalance:

networks:
  coofinet:
    driver: bridge
